### ISSUE TITLE
Missing Components

### ISSUE THREAD

**Issue by valiukasd** [jareer12/Tailwind-Css-UI-Components#4]
It looks like Tailwind added new components

An example would be [Stats](https://tailwindui.com/components/marketing/sections/stats-sections) in Marketing -> Page Sections

It would be nice if you could add the missing components :)

**Comment by valiukasd** [comment]
> https://anonfiles.com/vf36J3sdyc/TAILWIND_UI_Templates_zip <--- you can find them here

Thank you so much!

**Comment by jareer12** [comment]
Complete as of 19/1/2023

**Comment by HamasakiBrain** [comment]
It would be nice if you could add Ecommerce for figma the missing components :)
