### ISSUE TITLE
Code: DEPLOYMENT_NOT_FOUND

### ISSUE THREAD

**Issue by gokalpcayci** [jareer12/Tailwind-Css-UI-Components#5]
vercel app is not working

**Comment by HamasakiBrain** [comment]
check this [Link](https://tailwind-css-ui-components-xi.vercel.app/components/)

**Comment by HamasakiBrain** [comment]
> vercel app is not working

check this [Link](https://tailwind-css-ui-components-xi.vercel.app/components/)

**Comment by getlaurekt** [comment]
![image](https://user-images.githubusercontent.com/58201840/218613471-e18e2979-4e7f-432a-a467-370b9934229e.png)
Just sayin
